### ISSUE TITLE
Error starting rsense

### ISSUE THREAD

**Issue by ldmplus** [ianhattendorf/autocomplete-ruby#34] opened 2017-04-05 03:34 UTC
When the atom is started, it appears:
autocomplete-ruby: exec error: Error: Command failed: /Users/v/.rvm/gems/ruby-2.3.3/bin/rsense start --port 47367 --path /Users/v/Downloads/ApiServer
env: ruby_executable_hooks: No such file or directory
(You might need to set the rsense path, see the readme)

But the above command can be excuted in CMD.

**Comment by stevemeisner** [comment] 2017-04-07 20:43
I am having the same issue. Also using RVM. Also can run the command with no errors.

I am also using [atom-project-shell-env](https://github.com/ddiachkov/atom-project-shell-env) which seems to be correctly mapping the location (as the error shows the correct path without putting it in the rsense settings).

I imagine that I'm not doing _something_ right... help? :-)

**Comment by stevemeisner** [comment] 2017-04-07 21:18
I've got it working!

In the settings, instead of 

`/Users/username/.rvm/gems/ruby-2.3.3/bin/rsense`

i changed it to

`~/.rvm/gems/ruby-2.3.3/bin/rsense`

and it worked!

**Comment by ianhattendorf** [comment] 2017-04-12 02:31
I'm confused, `~` is a substitution for `/Users/username` assuming you're logged in as `username`. Could you try setting it back to `/Users/{your_username}/.rvm/gems/ruby-2.3.3/bin/rsense` and running again?

Also, are you launching from the icon, or from your terminal by running `atom`? I've noticed some issues where the environment isn't configured correctly when launching from the icon but is fine when launching from the terminal. If it works fine when launching via the terminal (executing `atom`) but not when you click the icon, then there's an issue with your environment configuration.

**Comment by turnspike** [comment] 2017-04-12 12:41
I'm also having this issue under zsh/chruby. Atom seems to inconsistently use gem locations for autocomplete-ruby.

Workaround:
1. Atom>Prefs>Autocomplete, set Rsense path to a specific chruby/rsense location: /Users/work/.gem/ruby/2.2.3/bin/rsense
2. Terminal, cd to project folder then: chruby ruby-2.2.3; atom .

For RVM, I imagine that just launching atom from the terminal in the desired project folder could also work.

It is perhaps related to this core bug: https://github.com/atom/atom/issues/4126

**Comment by stevemeisner** [comment] 2017-04-12 17:51
@ianhattendorf I'm not entirely sure why, either. :-/ I had just tried it in desperation.

I presumed it had something to do with using RVM and the more relative pointer somehow made magic... (not really, but it did work...)

I do launch from the CL using `atom .` in the project dir.

I'm a little embarrassed right now, as I did put a little time into troubleshooting a very real issue that I was having. But now that I'm going back and trying:

`/Users/stevemeisner/.rvm/gems/ruby-2.4.1/bin/rsense` (`// which rsense`)

...for the path in the settings, I am getting no errors. I also just removed the custom path from the settings, and the default also worked. I restarted Atom between each test.

Initially, I did have the same issue as @Sooyung. I suppose my PR isn't relevant after all. But now I'm not sure what fixed my issue.

**Comment by ianhattendorf** [comment] 2017-04-12 18:07
Yep, looks like the atom issue @turnspike mentioned is the root cause for this issue. Unfortunately there isn't much we can do on our end if the environment isn't configured correctly, so we'll need to wait for a fix in atom.

I'll go ahead and close this, if you have any other issues feel free to reply or open a new issue.

**Closed as completed by ianhattendorf** 2017-04-12 18:07 UTC

**Comment by stevemeisner** [comment] 2017-04-12 18:11
Thanks, @ianhattendorf for your attention and work here!

**Comment by ldmplus** [comment] 2017-04-27 09:38
Thanks everyone.

**Comment by blueacker** [comment] 2018-03-14 10:14
I also get this error message, and can't fix it by modifying rsense path. And I solved it by reinstalling autocomplete-ruby and autocomplete.

**Comment by ghost** [comment] 2018-03-27 17:14
use wrappers as stated at:
https://stackoverflow.com/questions/26247926/how-to-solve-usr-bin-env-ruby-executable-hooks-no-such-file-or-directory

> use wrappers, example:
> 
> $ which jekyll
> # /path/to/rvm/gems/ruby-version/bin/jekyll
> in the returned path replace bin with wrappers so you get:
> 
> /path/to/rvm/gems/ruby-version/wrappers/jekyll
> this is a script that will load proper environment and fix your problem, wrappers are generated automatically withing RVM.

**Comment by Schwad** [comment] 2018-06-29 10:08
So, this is quite embarrassing, but I am going to post this here because I had the same problem. 

I updated from Ruby 2.4.3 to Ruby 2.4.4 a while back. Didn't even think, realized that the reason I was getting this exact error is I didn't run `gem install rsense` again after the bump. so there you go, all fixed on my end.

**Comment by hardyoyo** [comment] 2019-01-28 15:55
None of the above workarounds worked for me. I think I will just disable autocomplete-ruby so I don't have to dismiss this error message in Atom any more.
